feat: support elastic index prefix
nevermined-io/marketplace-api pull request #170
Opened 2023-03-20 15:39 UTC by eruizgar91

## Description

Add a description of your changes here.

## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

2023-03-20 15:43 UTC, aaitor commented on .env.sample
> +ELASTIC_PREFIX="marketplace"
probably the name should be a bit more explicit. Like:
`ELASTIC_INDEX_NAME_PREFIX`

2023-03-20 15:43 UTC, aaitor commented on config/development.js
> +    prefix: process.env.ELASTIC_PREFIX,
change name

2023-03-20 15:45 UTC, aaitor commented on config/local.js.sample
> +    prefix: 'marketplace',
default should be empty

2023-03-20 15:45 UTC, aaitor commented on src/shared/config/config.service.ts
> +    prefix: Joi.string(),
empty by default

2023-03-20 16:02 UTC, dancespiele requested changes

2023-03-20 16:02 UTC, dancespiele commented on src/shared/elasticsearch/elastic.service.ts
> +        index: this.configService.get<string>('elasticsearch.prefix') + index,
here the same

2023-03-20 16:02 UTC, dancespiele commented on src/shared/elasticsearch/elastic.service.ts
> +        index: this.configService.get<string>('elasticsearch.prefix') + index,
here the same

2023-03-20 16:02 UTC, dancespiele commented on src/shared/elasticsearch/elastic.service.ts
> +      index: this.configService.get<string>('elasticsearch.prefix') + index,
here the same

2023-03-20 16:02 UTC, dancespiele commented on src/shared/elasticsearch/elastic.service.ts
> +      index: this.configService.get<string>('elasticsearch.prefix') + index,
here the same

2023-03-20 16:02 UTC, dancespiele commented on src/shared/elasticsearch/elastic.service.ts
> +      index: this.configService.get<string>('elasticsearch.prefix') + index,
here the same

2023-03-21 08:57 UTC, dancespiele approved these changes

2023-03-21 09:01 UTC, merged